### ISSUE TITLE
le hook github de mozfr ne marche plus

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/www#96]
Depuis la mise à jour du script,  le site ne se met plus à jour automatiquement, le webhook github ne donne pas d'erreur mais un git log montre que le site ne s'est pas mis à jour:
git log -n 1
commit 661d1a746f3fdb7890aadfd9a4113645f78c93df
Author: Théo Chevalier <theo.chevalier11@gmail.com>
Date:   Mon Dec 21 11:41:55 2015 +0100

**Comment by pascalchevrel** [comment]
Fatal error: Uncaught exception 'RuntimeException' with message 'The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly' in phar:///var/www/mozfr.org/www/sculpin.phar/vendor/composer/composer/src/Composer/Factory.php:53
Stack trace:
#0 phar:///var/www/mozfr.org/www/sculpin.phar/vendor/composer/composer/src/Composer/Factory.php(95): Composer\Factory::getHomeDir()
#1 phar:///var/www/mozfr.org/www/sculpin.phar/vendor/dflydev/embedded-composer-core/Dflydev/EmbeddedComposer/Core/EmbeddedComposerBuilder.php(124): Composer\Factory::createConfig()
#2 phar:///var/www/mozfr.org/www/sculpin.phar/bin/sculpin.php(69): Dflydev\EmbeddedComposer\Core\EmbeddedComposerBuilder->build()
#3 phar:///var/www/mozfr.org/www/sculpin.phar/bin/sculpin-phar-stub(16): include('phar:///var/www...')
#4 /var/www/mozfr.org/www/sculpin.phar(9): require('phar:///var/www...')
#5 {main}
  thrown in phar:///var/www/mozfr.org/www/sculpin.phar/vendor/composer/composer/src/Composer/Factory.php on line 53

**Comment by pascalchevrel** [comment]
```php
// CHECK: Download composer in the app root if it is not already there
if (! file_exists($composer) and file_exists($app_root.'/composer.json')) {
```

Mais composer.json a été supprimé dans https://github.com/mozfr/www/commit/a51759ad85a3dd23c9f64b70ca9521721bf3acae#diff-36cd38f49b9afa08222c0dc9ebfe35eb

Donc on ne crée plus la variable d'environnement

**Comment by pascalchevrel** [comment]
ok, je pense que c'est réparé, faudra garder un œil dessus
